server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_eb6ab9650716
    token: Z2ee
    app-id: wxd91381e783d5210f
    app-secret: cc8acd5e2a1477f8859362283efa646f
    template_id: vjK_0l4tTQP6oA7xJ74iJc0TEsXcXpm3Jvp29j8FGU8

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://117.72.220.242:13306/pay-mail?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
#    url: jdbc:mysql://117.72.220.242:13306/pay-mail?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000150663814
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC1UEIPSTUHkx+RsKemossHR5rQ4YvQ3w/Zr39cBSLp5qup5G46FYXNy3xqDQmT3FBWF32MVBHBlfP2dk+jEmKn+WzePWbvVrLmESZGrQC76shcSrnU0dX+Q8D2QSD8AoWP06lSB3OFf4ozAZb9thsDMEh367ao2TGfKK3mCjVqDgZHPvMyJStSjc9D5twMoCvGmg61tu3QdENtvqzpRs0X9FMMibbLl8cxdg5BVtLZntZ57C3bWgdng8fmVqI2iGjT7Y8jvUBJqJJ6E6sgxeMI5lQEabzSlkBUSRRpfYBn6+CKoNiCA0uBCJeHuS9NQ/+l4v25qHpjiPvi37JON1x3AgMBAAECggEAN22wtEGaD5W/iedqaTvNO419W6wH9TOsAc1v7u63DLBy/D4UIHeh7xbtEvKnYedxO9B0lijBQOAZs9fZYq3lMRrEWHCG/lYP3NuTSvnqhogw9l31z4TSmaeW3vFsJv6SXDTFx4j1nPMviYZL5YX9Xg0tqlOKBLZZQCHMf83RJHlfHUlJZiQ5kcAIqAQU+IayLxrBD1/lSFPvNxv8gGJud16rQYa9ojJ8X4vtfXMzpk6pX5D0iXhAAiGi4HsWWcKfHmYoIIyuxUrIvKC5N2HLZ+lCR7ROvAt8jFRvCv0H0/2ImZKrBShulmDffK07xpOpT1yp0U+mcoddvbw7x6fvYQKBgQDloebOkO5S3+hmo05rbT3gLEaQfRXBDWmlX/p7JAaD/XqiIlc9XS5awzyitCVvtRw9G5ZngLUTdtniS7kl8JoLtrj9Wgw/Nz1TkK/B907ibkagHDzXDSme3zdpkUz04W97uj7tspvGQSGR9DDLUWRyQzQh1x5/cYYqjybDK1JOJwKBgQDKIgK3P2f981W1mWRo2JS4Nx8Qdas/fbUNJ6AxJwbGeutT0IBaHTVY7nTzX33CCR+qeY9cwRXc3x/fawgd81l+NTlKXVbnq5pbRdSjGc/mK7siR9jKHan0ri9vOz2uypYLM/sTQO2MZQ3NuyJePIJ+gxMfbYc16XCJK6Bhtv3BMQKBgQCnUsOlvQGLrc/gChr4OE+f62M3oY2acDWM5VTVKbj9sFQNlExRUHaYeC7Ut8OXlDaRaGq93JEVL8MwG9E7jggRhQFiypyl65BqNcF76sK2R3h67lh+sv6i3y+3YsLapPHhDCMSfNT5LzhQ68gqPpKcl8+C4Qc+AfCrTkgGaqi8fQKBgGOTP51AWh1ra1SrvSA9WX4qgV4daYA8kB1r4Ol13UuXsCg49ZHvA6HMzsY5y3zz+6qCedJquDd3n37zfisq/3JCC/gLZU15ZvABxY+Xnqg38NchZ7WhyWDlEi8MkwVxfVsFf3FrsdpQye0IfBTKYEqsjZYU4d/4IN0iJb8dY4JxAoGBAJrP16Av2qijGkNzbiEaiRxNTmGP3phvv+o3F0GDWUAaBeDnPqn59qxS0mcCkWxpNx8q7QyGBP0r6z8hQ7jGvinw6IOG/jJS2umWnLh0d2mTVQaZVcYiQ03icJuzv/t5GM+Es1AArotLpJBDhF0LmMtBI1n+v0+2UAVzGzoh9MDd
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvZQHCytJLfI4otNlXo+0B5b/mrzJ41QH8P1FKVyXnIQ8WuHhInr9NmR6vQtp5Gki3L5XexF6xqk0oLdNVe3i0D0EQjRjHOyMw0ZWPKTbSZbPmzRXNHFmRbJ74Aa30dyg2xJR2xS4aNHuBMkBTToDWeKTI+3ydkHuBnsU9hSk81kCRA2bchmjDMMgrFluFg3DZ7v9+CNYK40jl2RCCLWvbTPHhkm/wiQiIAhvtghfIMMFsLconG7E3TidC89Aq7T9ijnLjro60SLdtrX8hELR1tN8/USONCrZDec9cIUqKhbOOzI+TudEvhOAgufD6+2Vva2dV60jB/1mXM+bfzhWtQIDAQAB
  notify_url: http://xfg-studio.natapp1.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml